/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => RelayMdPLugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  base_uri: "https://api.relay.md",
  api_key: "",
  vault_base_folder: "relay.md"
};
var RelayMdPLugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerObsidianProtocolHandler("relay.md:access-token", (params) => {
      if (!params.token) {
        return;
      }
      this.settings.api_key = params.token;
      this.settings.base_uri = DEFAULT_SETTINGS.base_uri;
      this.saveSettings();
      new import_obsidian.Notice("Access credentials for relay.md have been succesfully installed!");
    });
    this.addCommand({
      id: "send-current-active-file",
      name: "Send current open file",
      callback: async () => {
        new import_obsidian.Notice("Sending document to relay.md");
        const activeFile = this.app.workspace.getActiveFile();
        await this.send_document(activeFile);
      }
    });
    this.addCommand({
      id: "fetch-documents",
      name: "Retreive recent files",
      callback: async () => {
        new import_obsidian.Notice("Retreiving documents from relay.md");
        await this.get_recent_documents();
      }
    });
    this.registerEvent(this.app.metadataCache.on("changed", (file) => {
      if (file instanceof import_obsidian.TFile) {
        this.send_document(file);
      }
    }));
    this.registerEvent(this.app.vault.on("create", (file) => {
      if (file instanceof import_obsidian.TFile) {
        this.send_document(file);
      }
    }));
    this.registerInterval(window.setInterval(() => {
      this.get_recent_documents();
    }, 5 * 60 * 1e3));
    this.addSettingTab(new RelayMDSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async upsert_document(folder, filename, body) {
    if (!(this.app.vault.getAbstractFileByPath(folder) instanceof import_obsidian.TFolder)) {
      folder.split("/").reduce(
        (directories, directory) => {
          directories += `${directory}/`;
          try {
            this.app.vault.createFolder(directories);
          } catch (e) {
          }
          return directories;
        },
        ""
      );
    }
    const full_path_to_file = (0, import_obsidian.normalizePath)(folder + "/" + filename);
    const fileRef = this.app.vault.getAbstractFileByPath(full_path_to_file);
    if (fileRef === void 0 || fileRef === null) {
      await this.app.vault.create(full_path_to_file, body);
      new import_obsidian.Notice("File " + full_path_to_file + " has been created!");
    } else if (fileRef instanceof import_obsidian.TFile) {
      await this.app.vault.modify(fileRef, body);
      new import_obsidian.Notice("File " + full_path_to_file + " has been modified!");
    }
  }
  async load_document(id) {
    const options = {
      url: this.settings.base_uri + "/v1/doc/" + id,
      method: "GET",
      headers: {
        "X-API-KEY": this.settings.api_key,
        "Content-Type": "text/markdown"
      }
    };
    const response = await (0, import_obsidian.requestUrl)(options);
    try {
      const filename = response.headers["x-relay-filename"];
      const relay_to = JSON.parse(response.headers["x-relay-to"]);
      const body = response.text;
      for (const to of relay_to) {
        const tos = to.split("@", 2);
        const team = tos[1];
        const topic = tos[0];
        let full_path_to_file = this.settings.vault_base_folder + "/";
        if (team != "_")
          full_path_to_file += team + "/";
        full_path_to_file += topic;
        this.upsert_document(full_path_to_file, filename, body);
      }
    } catch (e) {
      console.log(JSON.stringify(e));
      throw e;
    }
  }
  async get_recent_documents() {
    const options = {
      url: this.settings.base_uri + "/v1/docs",
      method: "GET",
      headers: {
        "X-API-KEY": this.settings.api_key,
        "Content-Type": "application/json"
      }
    };
    const response = await (0, import_obsidian.requestUrl)(options);
    if (response.json.error) {
      console.error("API server returned an error");
      new import_obsidian.Notice("Relay.md returned an error: " + response.json.error.message);
      return;
    }
    try {
      response.json.result.map(async (item) => {
        new import_obsidian.Notice("Obtaining " + item["relay-filename"]);
        await this.load_document(item["relay-document"]);
      });
    } catch (e) {
      console.log(JSON.stringify(e));
      throw e;
    }
  }
  async send_document(activeFile) {
    if (!activeFile) {
      return;
    }
    if (activeFile.extension !== "md") {
      return;
    }
    const metadata = this.app.metadataCache.getCache(activeFile.path);
    if (!metadata || !metadata.frontmatter) {
      return;
    }
    if (!("relay-to" in metadata.frontmatter)) {
      return;
    }
    if (activeFile.path.startsWith(this.settings.vault_base_folder + "/")) {
      console.warn(
        "Files from the relay.md base folder cannot be sent."
      );
      return;
    }
    const id = metadata.frontmatter["relay-document"];
    const body = await this.app.vault.cachedRead(activeFile);
    let method = "POST";
    let url = this.settings.base_uri + "/v1/doc?filename=" + encodeURIComponent(activeFile.name);
    if (id) {
      method = "PUT";
      url = this.settings.base_uri + "/v1/doc/" + id;
    }
    console.log("Sending API request to api.relay.md (" + method + ")");
    const options = {
      url,
      method,
      headers: {
        "X-API-KEY": this.settings.api_key,
        "Content-Type": "text/markdown"
      },
      body
    };
    const response = await (0, import_obsidian.requestUrl)(options);
    if (response.json.error) {
      console.error("API server returned an error");
      new import_obsidian.Notice("Relay.md returned an error: " + response.json.error.message);
      return;
    }
    try {
      const doc_id = response.json.result["relay-document"];
      app.fileManager.processFrontMatter(activeFile, (frontmatter) => {
        frontmatter["relay-document"] = doc_id;
      });
    } catch (e) {
      console.log(e);
    }
  }
};
var RelayMDSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app2, plugin) {
    super(app2, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Base API URI").setDesc("Base URL for API access").addText((text) => text.setPlaceholder("Enter your API url").setValue(this.plugin.settings.base_uri).onChange(async (value) => {
      this.plugin.settings.base_uri = value;
      await this.plugin.saveSettings();
    }));
    if (this.plugin.settings.api_key === DEFAULT_SETTINGS.api_key) {
      new import_obsidian.Setting(containerEl).setName("API Access").setDesc("Authenticate against the relay.md API").addButton(
        (button) => button.setButtonText("Obtain access to relay.md").onClick(async () => {
          window.open("https://relay.md/configure/obsidian");
        })
      );
    } else {
      new import_obsidian.Setting(containerEl).setName("API Access").setDesc("Authenticate against the relay.md API").addButton(
        (button) => button.setButtonText("reset").onClick(async () => {
          this.plugin.settings.api_key = DEFAULT_SETTINGS.api_key;
          await this.plugin.saveSettings();
          this.display();
        })
      );
    }
    new import_obsidian.Setting(containerEl).setName("Vault relay.md inbox").setDesc("Base folder to synchronize into").addText((text) => text.setPlaceholder("relay.md").setValue(this.plugin.settings.vault_base_folder).onChange(async (value) => {
      this.plugin.settings.vault_base_folder = value;
      await this.plugin.saveSettings();
    }));
  }
};
